### ISSUE TITLE
simple django case - too early for that?

### ISSUE THREAD

**Issue by dPeS** [dropbox/pyston#1297]
pyston-0.5.1-linux64/test01$ ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
July 18, 2016 - 11:03:28
Django version 1.9.7, using settings 'test01.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[18/Jul/2016 11:03:36] "GET /admin HTTP/1.1" 301 0
[18/Jul/2016 11:03:36] "GET /admin/ HTTP/1.1" 302 0
../../src/runtime/str.cpp:1897: pyston::Box* pyston::strPartition(pyston::BoxedString*, pyston::BoxedString*): Assertion `PyString_Check(sep)' failed: 
Someone called abort!
Traceback (most recent call last):
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/from_cpython/Lib/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/from_cpython/Lib/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/from_cpython/Lib/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/from_cpython/Lib/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/from_cpython/Lib/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/venv/site-packages/django/core/servers/basehttp.py", line 99, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/from_cpython/Lib/SocketServer.py", line 649, in __init__
    self.handle()
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/venv/site-packages/django/core/servers/basehttp.py", line 176, in handle
    self.rfile, self.wfile, self.get_stderr(), self.get_environ()
  File "/home/pepto/Downloads/pyston-0.5.1-linux64/venv/site-packages/django/core/servers/basehttp.py", line 151, in get_environ
    path = path.partition('?')[0]
Aborted (core dumped)

to repro:

./pyston virtualenv/virtualenv.py venv
source venv/bin/activate
pip install django
django-admin startproject test01
cd test01
./manage.py startapp app01
./manage.py migrate
./manage.py runserver

browser -> localhost:8000/admin

tested on ubuntu 16.04 / amd64 pyston 0.5.1

**Comment by undingen** [comment]
thanks for the bug report, I fixed the issue :-)
